# Generated by Django 3.2.10 on 2022-01-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatblah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion', models.CharField(max_length=250)),
                ('cantidad', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
    ]
