# Generated by Django 3.2.10 on 2022-01-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatblah', '0003_auto_20220114_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
