# Generated by Django 3.2.10 on 2022-01-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatblah', '0004_alter_pedidos_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='telefono',
            field=models.CharField(max_length=16),
        ),
    ]
