# Generated by Django 3.2.10 on 2022-01-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatblah', '0005_auto_20220118_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sesiones',
        ),
    ]
